Fetched API key from env file
razor-network/oracle-node pull request #1048
Opened 2023-01-10 08:21 UTC by Yashk767

# Description

Fetched API key from env file when jobs need a API key
Fixes #1002

2023-01-10 08:31 UTC, Yashk767 commented
While creating a job which requires a API key, we need to follow a pattern which is defined in constants.go.

e.g. if this is the required format for this API
```
/v1/exchangerate/BTC?apikey=73034021746739393292922SAMPLE-KEY
```

Than we can create a job following this,
```
/v1/exchangerate/BTC?apikey={{API_KEY}} 
```

You can the definition here,
https://github.com/razor-network/oracle-node/pull/1048/files#diff-d5ab1755a1badc517f3a8eda33d72004f1aaca97998a7e2a24580f1c466fb1d2R55

is this fine @ashish10677 @SkandaBhat ?

If this is fine then we can convert the PR to ready for review.

2023-01-10 08:44 UTC, Yashk767 commented
In env file, 
jobName_API_KEY should be used as a keyword.

e.g. If the jobName which requires API key is `eth_Job`,
then the env file should have 
```
eth_Job_API_KEY = 6fa741de1bdd1d91830ba
```

2023-01-23 07:04 UTC, Yashk767 commented on utils/asset.go
> +		keywordWithDollar := `$` + keyword
Use this from contstants.go

2023-01-23 07:08 UTC, Yashk767 commented on utils/asset.go
> +			keywordWithDollar := `$` + keyword
Pick this up from constants.go

2023-02-02 09:03 UTC, Yashk767 commented
While defining the job which requires a API key, you need to start the keyword with regex defined in constants.go, which is set to `$`. 

e.g. if this is the required format for this API
```
/v1/exchangerate/BTC?apikey=73034021746739393292922
```

Than we can create a job following this,
```
/v1/exchangerate/BTC?apikey=$COINAPI_API_KEY
```

 Now you will youe the same keyword defined after $ in env file.
In env file,
```
COINAPI_API_KEY = 73034021746739393292922
```

2023-02-02 09:12 UTC, ashish10677 requested changes

2023-02-02 09:12 UTC, ashish10677 commented on utils/api.go
> +					request, err := http.NewRequest("GET", dataSourceURLStruct.URL, nil)
Move the processing part after the if inside a new function.
It should be something like this:

```
switch(dataSourceURLStruct.Type) {
    case "GET":
            processGetRequest()
    case "POST": 
           processPostRequest()
    default:
          return error
}
```

2023-02-02 10:10 UTC, ashish10677 approved these changes

2023-02-02 10:50 UTC, merged

2023-02-06 04:55 UTC, yohanelly95 commented
in alpha release

2023-08-03 05:38 UTC, Yashk767 commented
As suggested
```
// API key should be directly fetched from os environment 
// Use os.Getenv() as used here https://gobyexample.com/environment-variables instead of depending on godotenv library.
// Followed format {API_KEY_KEYWORD} as regex in urls to search for keyword and respective value from os env variables. 
```
Implemented the same in https://github.com/razor-network/oracle-node/pull/1097

While defining the job which requires a API key, staker needs to follow  regex defined in constants.go , which is set to e.g `${API_KEY_KEYWORD}`. 

e.g. if this is the required format for this API
```
https://api.gemini.com/v1/pubticker/v1/exchangerate/BTC?apikey=73034021746739393292922
```

Than a job with url can be created as shown below,
```
https://api.gemini.com/v1/pubticker/v1/exchangerate/BTC?apikey=$COINAPI_API_KEY
```

 Now staker needs to use the same keyword defined inside ${...} as a environment variable and assigning it a value as users API key as shown below.

```
COINAPI_API_KEY = 73034021746739393292922
```

Oracle node will directly look for the same in os environment variables and pick the respective value.
@ashish10677 @SkandaBhat