Added support for jobs returning hex values
razor-network/oracle-node pull request #1058
Opened 2023-03-01 09:36 UTC by Yashk767

# Description

- Added a new field `returnType` in dataSourceUrl struct which will support jobs returning values other than decimal values.
- Job returning hex values will be supported.
- Removed method caller for functions wherever it was not required to avoid mocking.

Fixes #1057

2023-04-14 07:32 UTC, ashish10677 requested changes

2023-04-14 07:32 UTC, ashish10677 commented on utils/asset_test.go
> +	//job2 := bindings.StructsJob{Id: 1, SelectorType: 0, Weight: 100,
If this is not needed remove this. If this is needed, uncomment.

2023-04-17 09:40 UTC, Yashk767 commented
Requested changes done and replaced alchemy RPC for tests, prior one was failing authentication. @ashish10677

2023-04-17 13:04 UTC, ashish10677 approved these changes

2023-04-17 13:04 UTC, merged