Feature/v1.1.0
razor-network/oracle-node pull request #1154
Opened 2023-10-13 11:03 UTC by SkandaBhat

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Contracts version:
* Hardware:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-16 07:32 UTC, SkandaBhat commented on cmd/commit.go
> +func CalculateSeed(client *ethclient.Client, account types.Account, keystorePath string, epoch uint32) ([]byte, error) {
Why was this change made? What exactly changed here?

2023-10-16 07:42 UTC, Yashk767 commented on cmd/commit.go
> +func CalculateSeed(client *ethclient.Client, account types.Account, keystorePath string, epoch uint32) ([]byte, error) {
As we are storing commit data before checking its transaction status, we had to add an additional verification while fetching data from commit data file. So to verify it was to seed calculation, so to avoid redundant code, seed calculation was separated to separate function.
Commit flow - https://www.notion.so/razorto/Oracle-Node-Alpha-Test-Suite-2a7128a3778b4332866931ee1a657ea4?pvs=4#f7b6e30cc46149faba90aa7be63d63e7

2023-10-16 07:45 UTC, SkandaBhat commented on config.sh
> +if [ -z "$ALTERNATE_PROVIDER" ]; then
Please follow DRY.

This can be rewritten:

```if [ -z "$ALTERNATE_PROVIDER" ]; then
   $RAZOR setConfig -p $PROVIDER -b $BUFFER -g $GAS_MULTIPLIER -w $WAIT_TIME --gasprice $GAS_PRICE --gasLimit $GAS_LIMIT --rpcTimeout 10 --httpTimeout 10 --logFileMaxSize $MAX_SIZE --logFileMaxBackups $MAX_BACKUPS --logFileMaxAge $MAX_AGE
 else
 $RAZOR setConfig -p $PROVIDER --alternateProvider "$ALTERNATE_PROVIDER" -b $BUFFER -g $GAS_MULTIPLIER -w $WAIT_TIME --gasprice $GAS_PRICE --gasLimit $GAS_LIMIT --rpcTimeout 10 --httpTimeout 10 --logFileMaxSize $MAX_SIZE --logFileMaxBackups $MAX_BACKUPS --logFileMaxAge $MAX_AGE
```

2023-10-16 07:48 UTC, SkandaBhat commented on core/constants.go
> +var ChainId = big.NewInt(0x5a79c44e)
Please add a comment here which says which chainId is being used.

2023-10-16 08:19 UTC, SkandaBhat commented on utils/api.go
> +	if cachedErr != nil {
There is a lot of code repitition in this block. Please rewrite so that its easy to understand and follows DRY.

2023-10-16 08:20 UTC, SkandaBhat commented on utils/api.go
> +	if cachedErr != nil {
Its more idiomatic in Go to check for ```cachedErr == nil``` and return early, reducing the level of indentation for the main logic.

2023-10-16 08:38 UTC, SkandaBhat commented on utils/asset.go
> +func ReplaceValueWithDataFromENVFile(re *regexp.Regexp, value string) string {
Can be rewritten to be much cleaner:

```func ReplaceWithEnvValue(re *regexp.Regexp, value string) string {
    substrings := re.FindAllString(value, -1)
    replacedKeywords := make(map[string]bool)

    for _, keyword := range substrings {
        if _, replaced := replacedKeywords[keyword]; !replaced {
            envValue, exists := os.LookupEnv(keyword)
            if exists {
                value = strings.Replace(value, keyword, envValue, -1)
                replacedKeywords[keyword] = true
            }
            // Handle the case where the environment variable doesn't exist, if necessary
        }
    }
    return value
}
```

2023-10-16 08:39 UTC, SkandaBhat commented on utils/asset.go
> +	for i := 0; i < len(substrings); i++ {
Why is for loop written like this? Should be

```
for _, keyword := range substrings {
```

2023-10-16 08:43 UTC, Yashk767 commented on utils/asset.go
> +	if strings.HasPrefix(job.Url, "{") {
We support both source: `job.url` being passed as direct url string which can be used for direct GET jobs and
source being passed as JSON formatted string, this was mainly added for POST requests but can be used or POST jobs and GET jobs passed in the form of struct
```
"source": {
      Type       string                 `json:"type"`
	URL        string                 `json:"url"`
	Body       map[string]interface{} `json:"body"`
	Header     map[string]string      `json:"header"`
	ReturnType string                 `json:"returnType"`
    }
```

so ` strings.HasPrefix(job.Url, "{") {` identifies that source is passed as JSON formatted string so it would be treated as job passed as struct and decoded accordingly.

2023-10-16 09:04 UTC, SkandaBhat commented on utils/math.go
> +func ManageReturnType(num interface{}, returnType string) (interface{}, error) {
Function name is super vague. Rename it to something more specific for eg:

```
ConvertToReturnType
```

```
TransformToReturnType
```

2023-10-16 09:07 UTC, SkandaBhat commented on utils/math.go
> +func ManageReturnType(num interface{}, returnType string) (interface{}, error) {
Seems to be just converting hex to int.

2023-10-16 09:08 UTC, SkandaBhat commented on utils/math.go
> +func ManageReturnType(num interface{}, returnType string) (interface{}, error) {
This entire function can be simplified:

```
func ConvertHexToInt(hexValue string) (int64, error) {
    // Removing "0x" prefix from hex value, if present
    hexValue = strings.TrimPrefix(hexValue, "0x")
    
    // Converting the given hex value to its decimal representation
    decimalValue, err := strconv.ParseInt(hexValue, 16, 64)
    if err != nil {
        log.Errorf("Error converting hex value %v to integer: %v", hexValue, err)
        return 0, err
    }
    
    return decimalValue, nil
}
```

2023-10-16 09:13 UTC, SkandaBhat commented on utils/api.go
> +func AddHeaderToRequest(request *http.Request, headerMap map[string]string) (*http.Request, error) {
This function seems to have multiple responsibilities:
- checking if a header value matches an API key pattern and replacing it with an environment variable
- adding headers to an HTTP request.

But the name `AddHeaderToRequest` suggests that it does only one thing. Move out the different logics into different functions and refactor.

2023-10-16 09:14 UTC, SkandaBhat commented on utils/api.go
> +		re := regexp.MustCompile(core.APIKeyRegex)
why is this done inside the loop? we are calculating again and again when this can be done only once outside the loop.

2023-10-16 09:14 UTC, SkandaBhat commented on utils/api.go
> +	return request, nil
are there no error scenarios for the function?

2023-10-16 09:16 UTC, SkandaBhat commented on utils/api.go
> +	request, err := http.NewRequest(dataSourceURLStruct.Type, dataSourceURLStruct.URL, requestBody)
dataSourceURLStruct.Type can be anything. Needs to be validated before creating a new request.

2023-10-16 09:18 UTC, SkandaBhat commented on utils/api.go
> +	if response.StatusCode != 200 {
there can be many status code responses that are other than 200 that are successful. 

https://stackoverflow.com/a/55210335

2023-10-16 09:20 UTC, SkandaBhat commented on utils/api.go
> +		return nil, errors.New("unable to reach API")
"unable to reach API" is misleading. Rewrite to something more appropriate.

2023-10-16 09:21 UTC, SkandaBhat reviewed
There are a lot of code quality improvements that are suggested in this PR. Please address all of them.

2023-10-16 09:21 UTC, Yashk767 commented on utils/math.go
> +func ManageReturnType(num interface{}, returnType string) (interface{}, error) {
This was being done in order to be open to more return types in future and all of them will be handled in the same function. Right now we support only hex thats why just kept hex the only case, Should I still rename?

2023-10-16 09:22 UTC, Yashk767 commented on utils/api.go
> +		re := regexp.MustCompile(core.APIKeyRegex)
Yes makes sense, will move it outside.

2023-10-16 09:24 UTC, SkandaBhat commented on utils/asset.go
> +	if strings.HasPrefix(job.Url, "{") {
There has to be a better way to identify this. cc: @ashish10677

2023-10-16 09:29 UTC, SkandaBhat commented on utils/math.go
> +func ManageReturnType(num interface{}, returnType string) (interface{}, error) {
There is no point keeping something customisable for the future. If it needs to be customisable, then it needs to be customisable right now.

The requirement for customisability seems very vague and open ended, and probably wont even warrant an updation in the future.

If you think this will be customised, then add all the customisations right now. In go, each function needs to have one responsibility and nothing else.

2023-10-16 09:31 UTC, Yashk767 commented on utils/api.go
> +	return request, nil
Yes there are no error cases for this, this function adds header to the request if present else return the same request. Makes sense, returning error can be removed from this function. Noted.

2023-10-16 09:34 UTC, Yashk767 commented on utils/api.go
> +	request, err := http.NewRequest(dataSourceURLStruct.Type, dataSourceURLStruct.URL, requestBody)
yes we do this inside `GetDataFromAPI()` where we call `ProcessRequest()` only for cases when  `dataSourceURLStruct.Type` is "GET" or "POST", else we return invalid request type.

2023-10-16 09:37 UTC, Yashk767 commented on utils/asset.go
> +	for i := 0; i < len(substrings); i++ {
yes this can be written like this as well. Suggested one is a good practise, will replace.

2023-10-16 10:07 UTC, ashish10677 commented on utils/asset.go
> +	if strings.HasPrefix(job.Url, "{") {
```
func isJSONCompatible(s string) bool {
    var temp interface{}
    err := json.Unmarshal([]byte(s), &temp)
    return err == nil
}
```

You can use this function to know whether the string is a JSON compatible string or a normal string. Use this instead of doing strings.HasPrefix().

2023-10-16 10:10 UTC, ashish10677 commented on utils/api.go
> +	if response.StatusCode != 200 {
```
// Success is indicated with 2xx status codes:
statusOK := response.StatusCode >= 200 && response.StatusCode < 300
if !statusOK {
    fmt.Println("Non-OK HTTP status:", response.StatusCode)
    // You may read / inspect response body
    return
}
```
You can use this @Yashk767

2023-10-16 10:23 UTC, ashish10677 commented on utils/api.go
> +		return nil, errors.New("unable to reach API")
```
return nil, fmt.Errorf("HTTP request failed with status code %d: %s", response.StatusCode, response.Status)
```
This can be used.

2023-10-16 10:40 UTC, ashish10677 commented
> @Yashk767 coverage seems to be decreasing here, any reason for it?

@Yashk767 add tests for the new functions.

2023-10-16 10:46 UTC, ashish10677 requested changes

2023-10-16 10:46 UTC, ashish10677 commented on cmd/commit.go
> +func CalculateCommitment(seed []byte, values []*big.Int) ([32]byte, error) {
Add tests for this function and CalculateSeed

2023-10-17 03:20 UTC, Yashk767 commented on utils/api.go
> +	if cachedErr != nil {
Yes makes sense - Go idioms favor early returns.

Currently `localCache.Read()` returns custom error `erros.New("data not present in cache")` when no data found in cache and this is the only error being returned else it returns cachedData without any error.

This can be done in a better way - by using a `boolean`  return instead of `error`.
So GetDataFromAPI() will be changed to
```
cachedData, found := localCache.Read(dataSourceURLStruct.URL)
	if found :
		log.Debugf("Getting Data for URL %s from local cache...", dataSourceURLStruct.URL)
		return cachedData, nil
	else :
                makeAPIRequest
 ```
Its more readable and favours early returns as well.

2023-10-17 03:40 UTC, Yashk767 commented on utils/asset.go
> +	if strings.HasPrefix(job.Url, "{") {
This `isJSONCompatible()` doesn't work in our case as technically a normal string "Hello" is also a valid JSON.

2023-10-17 04:58 UTC, Yashk767 commented on utils/math.go
> +func ManageReturnType(num interface{}, returnType string) (interface{}, error) {
Yes I did change the function. 
Here the function should rather look like `ConvertHexToInt(parsedData interface{})` where parameter should be of type `interface{}`as the input for function is parsed data from json which could be of any type.

If we stringify the parsed data and pass it as parameter, it will also convert the non string data type into string and can lead to invalid conversion.
So inside `ConvertHexToInt()` we return error if the data type is not hex string to avoid invalid conversions.

```
func ConvertHexToInt(num interface{}) (int, error) {
	switch v := num.(type) {
	case string:
		hexValue := strings.TrimPrefix(v, "0x")
		decimalValue, err := strconv.ParseInt(hexValue, 16, 64)
		if err != nil {
			log.Errorf("Error converting hex value %v to integer: %v", hexValue, err)
			return 0, err
		}
		return int(decimalValue), nil
	default:
		log.Errorf("Input data %v is not a hex value", num)
		return 0, errors.New("input data is not hex")
	}
}
```

2023-10-17 20:27 UTC, ashish10677 commented on utils/asset.go
> +	if strings.HasPrefix(job.Url, "{") {
But you're checking for strings beginning with `"{"`. By that logic "Hello" will fail for HasPrefix("{") as well

2023-10-17 20:44 UTC, ashish10677 requested changes

2023-10-17 20:44 UTC, ashish10677 commented on cmd/commit_test.go
> +					CommitmentHash: [32]byte{34, 201, 186, 7, 78, 68, 208, 0, 145, 22, 178, 68, 165, 206, 206, 158, 154, 222, 133, 175, 72, 110, 31, 79, 141, 184, 227, 4, 230, 96, 91, 234},
Instead of keeping it bytes,  a better practice would be to keep the data in hex, so that it is readable, can convert into bytes wherever required.

2023-10-18 00:03 UTC, Yashk767 commented on utils/asset.go
> +	if strings.HasPrefix(job.Url, "{") {
Hmm just rechecked this, actually `isJSONCompatible()` should work. Let me clearify, 
These are the outputs for `isJSONCompatible(job.Url)` for different `job.Url` cases.

```
CASE 1: "Hello":   is an invalid JSON
CASE 2: `"Hello"`: is a valid JSON
```

The outer quotes are part of the Go string, and the inner double quotes represent the JSON string.
so CASE 1 checks `Hello` as JSON string and return false.
and CASE 2 check `"Hello"` as JSON string which is true and valid as strings in JSON need to be wrapped in double quotes which is true in this case.

In our case of direct Url strings, isJSONCompatible() will work correctly.
```
e.g.

job.Url = "https://api.gemini.com/v1/pubticker/ethusd"
isJSONCompatible(job.Url) returns -> false

2023-10-18 06:10 UTC, Yashk767 commented on cmd/commit_test.go
> +					CommitmentHash: [32]byte{34, 201, 186, 7, 78, 68, 208, 0, 145, 22, 178, 68, 165, 206, 206, 158, 154, 222, 133, 175, 72, 110, 31, 79, 141, 184, 227, 4, 230, 96, 91, 234},
Yes its done in https://github.com/razor-network/oracle-node/pull/1154/commits/6401d80c617e99b9e65926f0ca568cf3720945d8
But it could not be done for `CommitmentHash` as it is a field inside defined `types.Commitment` struct so we cannot change its data type. and we cannot directly use `decodeHexToBytes(CommitmentHexValue)` in arguments as it returns `([]byte, error)`.
Else I have replaced  all the byte values with hex strings to be more readable at all possible places.

2023-10-18 06:33 UTC, ashish10677 commented on cmd/commit_test.go
> +					CommitmentHash: [32]byte{34, 201, 186, 7, 78, 68, 208, 0, 145, 22, 178, 68, 165, 206, 206, 158, 154, 222, 133, 175, 72, 110, 31, 79, 141, 184, 227, 4, 230, 96, 91, 234},
You can fix it actually. Suppose args is set up like this:
```
type args struct {
		values        []*big.Int
		commitment    string
		commitmentErr error
		secret        string
		secretErr     error
		salt          string
	}
```
And then, before this line:
```
			utilsMock.On("GetCommitment", mock.Anything, mock.Anything).Return(tt.args.commitment, tt.args.commitmentErr)
```
You convert the commitment string into byte and place it inside the struct.

2023-10-18 06:59 UTC, Yashk767 commented on cmd/commit_test.go
> +					CommitmentHash: [32]byte{34, 201, 186, 7, 78, 68, 208, 0, 145, 22, 178, 68, 165, 206, 206, 158, 154, 222, 133, 175, 72, 110, 31, 79, 141, 184, 227, 4, 230, 96, 91, 234},
Addressed it in https://github.com/razor-network/oracle-node/pull/1154/commits/06ee3fadda8c50eb07f7657a5d9b49a01e632ba3

2023-10-18 07:01 UTC, ashish10677 approved these changes

2023-10-18 09:45 UTC, SkandaBhat commented
Were negative test cases added?

```
var apiKeys = []string{
    "key123?break",
    "key&124break",
    "key=125break",
    "key#126break",
    "key+127break",
    "key%128break",
    "key/129break",
    "key?&=#+%/130",
}
```

Please confirm if these do not break the feature. cc: @ashish10677 @Yashk767

2023-10-18 11:42 UTC, merged

2023-10-18 15:39 UTC, Yashk767 commented
> Were negative test cases added?
> 
> ```
> var apiKeys = []string{
>     "key123?break",
>     "key&124break",
>     "key=125break",
>     "key#126break",
>     "key+127break",
>     "key%128break",
>     "key/129break",
>     "key?&=#+%/130",
> }
> ```
> 
> Please confirm if these do not break the feature. cc: @ashish10677 @Yashk767

Yes I checked this, `ReplaceValueWithDataFromENVFile()` does two things
1. Find keyword that match the regex pattern: 
     - This works fine for all the special characters.
2. For that keyword, the function uses `os.ExpandEnv(keyword)` to fetch its corresponding value from the environment variables:
      - `os.ExpandEnv(keyword)` also works fine as sexpected for all the special characters.
     
NOTE:
But just to note that the cases which contain `=` in their keyword are not valid keywords and can be users fault, as keyword is something which is set by user in environment variables.
And Windows/MacOs uses the equals `=` sign as a delimiter between names and values in its environment variable block
```     
 e.g. 
if you had an environment variable like MY=VAR=SomeValue, the system 
might misinterpret this as an environment variable named MY with the value 
VAR=SomeValue, which is not the intended result  
```

So `os.ExpandEnv()` in our function returns empty string if no keyword found in env variables which is a valid case.

CONCLUSION:
`ReplaceValueWithDataFromENVFile()` works as expected and handles all the possible edge cases mentioned above.

cc @SkandaBhat @ashish10677