feat: Fetched each job for each collection in a separate go routine
razor-network/oracle-node pull request #1168
Opened 2023-12-01 08:51 UTC by Yashk767

# Description

Fetching of jobs for a collection is implemented  in parallel.

Fixes https://linear.app/interstellar-research/issue/RAZ-599

# How Has This Been Tested?

Ran a staker on devnet set up, and also modified tests to look for values being reported correctly

2023-12-12 12:46 UTC, ashish10677 requested changes

2023-12-12 12:46 UTC, ashish10677 commented on utils/asset.go
> +	var wg sync.WaitGroup
Write this in one bracket:
```
var (
    mu sync.Mutex
    data []*big.Int
   .
   .
   .
)
```

2023-12-12 12:46 UTC, ashish10677 commented on utils/asset.go
> +		go func(job bindings.StructsJob) {
move this function out, and call it as `go funcName()`

2023-12-12 12:46 UTC, ashish10677 commented on utils/asset.go
> +				return
Why is there no logging of error, or sending error into an error channel?

2023-12-12 13:02 UTC, Yashk767 commented on utils/asset.go
> +				return
The error here is logged inside `GetDataToCommitFromJob()` so we don't log here, and we cannot return this error as we need to iterate over all other jobs so we just use `continue` keyword here. 
We don't accumulate these errors and we don't use this error so there was no need to send the job errors anywhere to a channel.

2023-12-18 04:48 UTC, ashish10677 commented on utils/asset.go
> +				return
So if there is no error, the default option is to proceed to the next job?

2023-12-18 05:51 UTC, Yashk767 commented on utils/asset.go
> +				return
yes

2023-12-19 05:28 UTC, Yashk767 commented on utils/asset.go
> +		go func(job bindings.StructsJob) {
Inside go routine we are only calling, `GetDataToCommitFromJobs` with job as a parameter, I don't think we need a separate function just for this right?

2023-12-19 05:30 UTC, Yashk767 commented on utils/asset.go
> +	var wg sync.WaitGroup
Done in https://github.com/razor-network/oracle-node/pull/1168/commits/a772e124ec8366c28c11e3fa7c3a32da4cc217fe

2023-12-20 06:09 UTC, ashish10677 commented on utils/asset.go
> +		go func(job bindings.StructsJob) {
But it is consuming space in this function, making this function bigger. It's better to move it out.

2023-12-20 11:31 UTC, Yashk767 commented on utils/asset.go
> +		go func(job bindings.StructsJob) {
Done in https://github.com/razor-network/oracle-node/pull/1168/commits/dca6b3335907419a709e11cfbf2c0f7e78bd27ba

2023-12-21 05:34 UTC, ashish10677 approved these changes

2023-12-21 05:36 UTC, merged