ci: added feature branches to github workflows
razor-network/oracle-node pull request #1186
Opened 2024-02-15 07:29 UTC by Yashk767

# Description

Added feature branches to github workflows

Fixes #1185 https://linear.app/interstellar-research/issue/RAZ-741

2024-02-15 07:59 UTC, ashish10677 approved these changes

2024-02-16 07:38 UTC, yohanelly95 requested changes

2024-02-16 07:38 UTC, yohanelly95 commented on .github/workflows/feature.yml
> +name: CI/CD Release Pipeline
imo separate file is not required, since the requirement is same as the develop.yml file, just the trigger needs to be added. Add a branch check for the docker build job to run only for develop trigger and not when pushed to feature branch.

2024-02-16 07:39 UTC, yohanelly95 commented on .github/workflows/feature.yml
> +name: CI/CD Release Pipeline
try updating the `develop` workflow file with the above changes.

2024-02-16 08:13 UTC, Yashk767 commented on .github/workflows/feature.yml
> +name: CI/CD Release Pipeline
Done in https://github.com/razor-network/oracle-node/pull/1186/commits/ef21a09975242e7e1f6f62e0a6be4a563b5867b4

2024-02-16 08:41 UTC, Yashk767 commented
ci is working fine as expected. 
Tests are failing, I can fix tests in some other PR @yohanelly95. can review and approve this.

2024-02-16 10:05 UTC, yohanelly95 commented
> ci is working fine as expected. Tests are failing, I can fix tests in my next PR @yohanelly95. can review and approve this.

I see, why are the tests failing? @Yashk767

2024-02-16 10:15 UTC, Yashk767 commented
> > ci is working fine as expected. Tests are failing, I can fix tests in my next PR @yohanelly95. can review and approve this.
> 
> I see, why are the tests failing? @Yashk767

There is a test where we fetch SKALE staging chainId using a POST request, as the chain is disabled now, the job is not responding. @yohanelly95

2024-02-19 04:30 UTC, yohanelly95 approved these changes

2024-02-19 05:54 UTC, merged