fix: incorrect state error for shorter epoch length
razor-network/oracle-node pull request #1192
Opened 2024-02-26 10:06 UTC by Yashk767

# Description

Transactions were missing state due to delayed state actions consuming more time than expected.
- This was due to higher values of config parameters `bufferPercent` and `wait`.
- And resetting of jobs/collections cache was part of main voting process which would consume some time.
 

Fixes 
https://linear.app/interstellar-research/issue/RAZ-755
https://linear.app/interstellar-research/issue/RAZ-758

# How Has This Been Tested?

Ran a staker on staging with updated config values.

2024-02-27 06:37 UTC, ashish10677 requested changes

2024-02-27 06:37 UTC, ashish10677 commented on cmd/config-utils.go
> +		MaxWaitTime = 5 // Maximum wait time in seconds
Are you sure 5 secs will be enough? Blockchain will give block mining confirmation in 5 secs?

2024-02-27 06:37 UTC, ashish10677 commented on cmd/vote.go
> +			go utils.ResetAssetCache(client)
When does this goroutine stop. Not using wait groups isn't a good thing.

2024-02-27 06:49 UTC, Yashk767 commented on cmd/config-utils.go
> +		MaxWaitTime = 5 // Maximum wait time in seconds
No no , this isn't `waitForBlockCompletion` time , this is wait time from the config.
we use this in the voting process during buffer state.

2024-02-27 06:54 UTC, Yashk767 commented on cmd/vote.go
> +			go utils.ResetAssetCache(client)
In `ResetAssetCache` we just reset cache where we delete the jobs/collections cache and initialise it again, after resetting this, go routine stops.

But yes I can add a validation using wait groups to make sure the go routine completes its execution, if not than report the error.

2024-02-27 07:36 UTC, ashish10677 commented on cmd/config-utils.go
> +		MaxWaitTime = 5 // Maximum wait time in seconds
Ok then fine.

2024-02-27 07:37 UTC, ashish10677 commented on cmd/vote.go
> +			go utils.ResetAssetCache(client)
Yes, please do. Without it this may cause uncertainities.
Do check the number of goroutines before and after closing this one, just to confirm, while testing.

2024-02-27 12:32 UTC, Yashk767 commented on cmd/vote.go
> +			go utils.ResetAssetCache(client)
Returned error when occurred in resetAssetCache go routine in https://github.com/razor-network/oracle-node/pull/1192/commits/d9eaa5f45799d5aa7f1abdd15ca24064a907e3fa

2024-02-28 05:24 UTC, rajkharvar submitted a review, later dismissed

2024-02-29 08:58 UTC, Yashk767 commented on cmd/vote.go
> +			go utils.ResetAssetCache(client)
As discussed, introduced go routine at the start which will handle resetting cache part - https://github.com/razor-network/oracle-node/pull/1192/commits/a87b16f5858e6d321fb292a7485ff5becfdb2dc4 @ashish10677

2024-02-29 11:33 UTC, ashish10677 approved these changes

2024-03-01 05:24 UTC, rajkharvar approved these changes

2024-03-01 07:51 UTC, merged