refactor: used a common http client for all the requests
razor-network/oracle-node pull request #1194
Opened 2024-03-19 09:54 UTC by Yashk767

# Description

Used a common http client to avoid opening a new connection on every `client.Do()` call for every API.
A single http client makes the node to reuse the existing connections from connection pool.

Fixes https://linear.app/interstellar-research/issue/RAZ-771

# How Has This Been Tested?

Ran a node on local and staging environment with 5 min epoch time.

2024-03-20 09:20 UTC, ashish10677 commented
@Yashk767 why are the tests failing?

2024-03-20 13:21 UTC, ashish10677 approved these changes

2024-03-28 10:03 UTC, SkandaBhat requested changes

2024-03-28 10:03 UTC, SkandaBhat commented on client/httpClient.go
> +var httpClient *http.Client
DO not use global variables. Use a struct and implement methods. cc: @ashish10677

2024-04-08 10:45 UTC, SkandaBhat commented
Closing this. Please reopen after updating.

2024-04-08 10:45 UTC, closed without merging