refactor: optimised fetching key from keystore dir
razor-network/oracle-node pull request #1196
Opened 2024-03-20 08:43 UTC by Yashk767

# Description

Previously, when fetching keys from the keystore, we used ks.Accounts(), which created a new goroutine every time. This approach led to goroutines waiting indefinitely, which was inefficient and could potentially cause resource exhaustion issues. To optimize this process and avoid unnecessary resource consumption, we have revised our method for fetching keystore files.

So this PR optimises keystore file fetching to prevent indefinite waiting by goroutines.

Fixes https://github.com/razor-network/oracle-node/issues/1195

Solution
We now iterate over all keystore files in the directory and select the file whose filename satisfies a specific regex pattern matching the input address. This approach ensures that only the relevant keystore file is fetched, improving efficiency by eliminating the need to fetch and examine all accounts with ks.Accounts().

How Has This Been Tested?
- Positive and Negative Scenarios: Implemented comprehensive tests that cover both positive and negative scenarios for the fetching of the keystore file. This ensures the functionality works as expected under various conditions.
- Account Imports: Tested the creation and importation of both new and old accounts to verify compatibility and functionality across different account types and ages.

2024-03-20 09:20 UTC, ashish10677 commented
Tests failing @Yashk767

2024-03-20 09:21 UTC, ashish10677 requested changes

2024-03-20 09:21 UTC, ashish10677 commented on accounts/accounts.go
> +		normalizedAddress = normalizedAddress[2:]
@Yashk767 Please check this suggestion. It's the right way.

2024-03-20 09:24 UTC, Yashk767 commented on accounts/accounts.go
> +		normalizedAddress = normalizedAddress[2:]
yes, some tests are failing, fixing those. Will push it together.

2024-03-20 13:23 UTC, ashish10677 commented on .github/workflows/ci.yml
> +          go-acc ./... --ignore razor/accounts/mocks --ignore razor/accounts/test_accounts --ignore razor/cmd/mocks
Why have you excluded `test_accounts`?

2024-03-21 05:33 UTC, Yashk767 commented on .github/workflows/ci.yml
> +          go-acc ./... --ignore razor/accounts/mocks --ignore razor/accounts/test_accounts --ignore razor/cmd/mocks
`test_accounts` directory has keystore files of testing addresses

2024-03-21 09:38 UTC, ashish10677 submitted a review, later dismissed

2024-03-28 09:43 UTC, SkandaBhat commented
`package accounts

import (
	"crypto/ecdsa"
	"github.com/ethereum/go-ethereum/accounts"
	"github.com/ethereum/go-ethereum/accounts/keystore"
	"razor/logger"
	"razor/path"
	"os"
	"strings"
)

type AccountManager struct {
	log *logger.Logger
	ks  *keystore.KeyStore
}

// NewAccountManager creates a new AccountManager instance.
func NewAccountManager() *AccountManager {
	return &AccountManager{
		log: logger.NewLogger(),
	}
}

// InitializeKeystore initializes the keystore instance.
func (am *AccountManager) InitializeKeystore(keystorePath string) {
	am.log.Info("Initialising keystoreInstance...")
	am.ks = keystore.NewKeyStore(keystorePath, keystore.StandardScryptN, keystore.StandardScryptP)
}

// CreateAccount creates a new account.
func (am *AccountManager) CreateAccount(keystorePath string, password string) accounts.Account {
	// Method implementation...
}

// GetPrivateKey retrieves the private key from the keystore.
func (am *AccountManager) GetPrivateKey(address string, password string, keystoreDirPath string) (*ecdsa.PrivateKey, error) {
	// Method implementation...
}

// SignData signs the data.
func (am *AccountManager) SignData(hash []byte, account types.Account, defaultPath string) ([]byte, error) {
	// Method implementation...
}
`

Please follow this pattern. cc: @ashish10677

2024-03-28 09:55 UTC, closed without merging