refactor: used the same keystore instance to fetch pKey everytime
razor-network/oracle-node pull request #1200
Opened 2024-04-05 09:14 UTC by Yashk767

# Description

Creating a new keystore instance for every transaction costed us an opening of separate goroutine which would start a watcher/updater to check the changes in the keystore directory files. Either creating the instance at the start and using the same instance every time  for a transaction would function the same and wouldnt cost up an extra goroutine.

- Created keystore instance at the start and reused the same for every transaction.
- Keystore defined as a field to `AccountManager` struct which is used as a method caller to `GetPrivateKey()`

Fixes https://github.com/razor-network/oracle-node/issues/1197

# How Has This Been Tested?

Ran a staker making transactions in voting process with a goroutine counter placed before and after the getPrivateKey call.

2024-04-11 11:38 UTC, ashish10677 requested changes

2024-04-11 11:38 UTC, ashish10677 commented on cmd/resetUnstakeLock.go
> -	log.Debugf("ExecuteExtendLock: Calling ResetUnstakeLock with arguments extendLockInput = %+v", extendLockInput)
Why is this log removed.

2024-04-11 11:38 UTC, ashish10677 commented on cmd/vote_test.go
> +			gotSignature, gotSecret, err := cmdUtils.CalculateSecret(account, tt.args.epoch, testKeystorePath, tt.args.chainId)
I think the error check should be first, only then gotSignature and gotSecret must be converted to string.

2024-04-11 12:46 UTC, Yashk767 commented on cmd/claimBounty.go
> -		log.Debugf("ExecuteClaimBounty: Calling ClaimBounty() with arguments redeem bounty input: %+v", redeemBountyInput)
`reedemBountyLockInput` struct has a password field in it so removed it from the logs while other parameters we do log inside `ClaimBounty()`. Same is being done in other scenarios.

2024-04-11 12:59 UTC, ashish10677 commented on cmd/claimBounty.go
> -		log.Debugf("ExecuteClaimBounty: Calling ClaimBounty() with arguments redeem bounty input: %+v", redeemBountyInput)
Okay makes sense.

2024-04-11 13:13 UTC, Yashk767 commented on cmd/vote_test.go
> +			gotSignature, gotSecret, err := cmdUtils.CalculateSecret(account, tt.args.epoch, testKeystorePath, tt.args.chainId)
Done in https://github.com/razor-network/oracle-node/pull/1200/commits/9218d2f3fe64728fd2b022f045798ceab67258e4

2024-04-12 05:54 UTC, ashish10677 approved these changes

2024-04-23 04:32 UTC, rajkharvar approved these changes

2024-04-26 10:42 UTC, merged