refactor: used a common http client for all the requests
razor-network/oracle-node pull request #1201
Opened 2024-04-11 10:16 UTC by Yashk767

# Description

There was a gradual increase in number of go routines for every http request that node was making, this was due to new HTTP client being used on every `httpClient.Do()` call. Rather there should be a common HTTP client which handles creating and making requests across all hosts, this will enable the reusing of existing connections from the connection pool.
   
- Used a common http client to avoid opening a new connection on every `client.Do()` call for every API.
- Removed global variable `HttpTimeout` and directly picked it up from config.

Fixes #1197 ,  https://linear.app/interstellar-research/issue/RAZ-771

# How Has This Been Tested?

Ran a node on local and staging environment with 5 min epoch time.

2024-04-11 12:42 UTC, ashish10677 requested changes

2024-04-11 12:42 UTC, ashish10677 commented on core/constants.go
> +var HTTPClientMaxIdleConns = 15
Use const instead of var for these

2024-04-11 12:52 UTC, Yashk767 commented on core/constants.go
> +var HTTPClientMaxIdleConns = 15
okay I will make this change.
While all the other constants defined in `constants.go` are also defined with `var` keyword. I think we can update to `const` at all these occurrences but in separate PR, not in this. Is this okay @ashish10677 ?

2024-04-11 12:58 UTC, ashish10677 commented on core/constants.go
> +var HTTPClientMaxIdleConns = 15
For others, you can open a new PR. For these new variables you've added, change it in this PR itself.

2024-04-11 13:13 UTC, Yashk767 commented on core/constants.go
> +var HTTPClientMaxIdleConns = 15
Done in https://github.com/razor-network/oracle-node/pull/1201/commits/897d867f12ee4075cb34e9934e42afacd7518d9c

2024-04-12 05:49 UTC, ashish10677 approved these changes

2024-04-23 05:23 UTC, rajkharvar approved these changes

2024-04-26 11:07 UTC, ashish10677 approved these changes

2024-04-26 11:12 UTC, merged