refactor: fetching jobs and collections from asset caches
razor-network/oracle-node pull request #1207
Opened 2024-04-24 09:38 UTC by Yashk767

# Description

- Stored jobs and collections in a cache and updating the cache on every collection/job update or creation.
- Faster fetching [O(1)] of jobs from cache for every collection/job resulting in quicker execution of commit process.

Fixes https://linear.app/interstellar-research/issue/RAZ-713

# How Has This Been Tested?

Tested with running a staker and creating create and update jobs/collections transactions and checked whether event listeners are listening correctly and updating the cache with the expected update value.

2024-05-07 12:07 UTC, ashish10677 requested changes

2024-05-08 10:00 UTC, Yashk767 commented on cmd/eventListeners.go
> +func scheduleResetCache(client *ethclient.Client, jobsCache *cache.JobsCache, collectionsCache *cache.CollectionsCache) {
Hmm yes we don't store any time sensitive data though in the asset caches, as the data stored is completely event-driven and updated regularly in the desired interval, I think we can avoid resetting. correct ?

2024-05-08 10:16 UTC, ashish10677 commented on cmd/eventListeners.go
> +func scheduleResetCache(client *ethclient.Client, jobsCache *cache.JobsCache, collectionsCache *cache.CollectionsCache) {
Yes. It's not required.

2024-05-10 06:40 UTC, ashish10677 commented on cmd/eventListeners.go
> +		return []Types.Log{}, nil
You're not returning error here @Yashk767

2024-07-22 11:28 UTC, ashish10677 requested changes

2024-07-22 11:28 UTC, ashish10677 commented on cmd/commit.go
> +	commitParams.LocalCache.StopCleanup()
Why do you need to call StopCleanup() here? It will wait for the cache goroutine to finish right?
But you've just initalized it in this function? Do you need to to start the cache and end it here itself?
I didn't understand this implementation. Please explain.

2024-07-22 21:11 UTC, Yashk767 commented on cmd/commit.go
> +	commitParams.LocalCache.StopCleanup()
No no, the `localCache` described here is the one which stores the result data from APIs. This has nothing to do with caches which we are using for assets.
Here the only change is `localCache` was passed as parameter to function earlier, but now `commitParams`struct instead is passed as a parameter which sub includes the field  `localCache`.

Thus the method caller changes from `localCache.StopCleanup()` to `commitParams.LocalCache.StopCleanup()`.

2024-07-30 09:07 UTC, Yashk767 commented on cmd/eventListeners.go
> +					updatedJob, err := utils.UtilsInterface.GetActiveJob(client, jobId)
`jobCreated` and `collectionCreated` events only provide `JobId` and `collectionId` when they are emitted.

2024-07-30 11:19 UTC, Yashk767 commented on cmd/eventListeners.go
> +					jobId := utils.ConvertHashToUint16(vLog.Topics[1])
Done in https://github.com/razor-network/oracle-node/pull/1207/commits/7d767b2b6b4dbc7e3e9c52a22b465bfdd6f84fee

2024-07-30 12:38 UTC, Yashk767 commented on cmd/eventListeners.go
> +	eventNames := []string{"JobUpdated", "CollectionUpdated", "CollectionActivityStatus", "JobCreated", "CollectionCreated"}
use these from constants

2024-07-30 13:09 UTC, Yashk767 commented on core/types/vote.go
> +	HttpClient                HttpClientInterface
Cant we directly use inbuilt *client.HttpClient instance instead of this custom HttpClient struct

2024-07-31 10:34 UTC, Yashk767 commented on core/types/vote.go
> +	HttpClient                HttpClientInterface
Done in https://github.com/razor-network/oracle-node/pull/1207/commits/f4514a70fffad796b4103a60679d17931bbdd6f8
@ashish10677 @rajkharvar

2024-07-31 12:39 UTC, ashish10677 approved these changes

2024-07-31 12:39 UTC, rajkharvar approved these changes

2024-07-31 13:23 UTC, merged