Yash/raz 834 update default config values to support 20 min epoch for
razor-network/oracle-node pull request #1209
Opened 2024-05-08 09:33 UTC by Yashk767

# Description

Updated the default, maximum and minimum config values in core/constants.go and cmd/config-utils.go` in order to support 20 min epoch which in place by default also supports shorter epoch of 5 min.

Fixes https://github.com/razor-network/oracle-node/issues/1208

2024-05-08 09:41 UTC, ashish10677 requested changes

2024-05-08 09:41 UTC, ashish10677 commented on config.sh
> +read -rp "Buffer Percent: (20) " BUFFER
20% buffer for 5 minutes is 1 minute in the beginning and 1 minute in the end. So that gives only 3 minutes to process things, and then contract buffer is also there on top of it. Is it okay?

2024-05-08 09:46 UTC, Yashk767 commented on config.sh
> +read -rp "Buffer Percent: (20) " BUFFER
No, this PR just brings back the 20 min support, so only the default, max values are changed for config parameters to support both 20 min and 5 min.
The dev release should support 20 min epoch by default so the default config values are changed for the same.

2024-05-08 09:48 UTC, ashish10677 commented on config.sh
> +read -rp "Buffer Percent: (20) " BUFFER
Okay, so if you want to run 5 min epoch, you'll change the values in your razor.yaml and run right?

2024-05-08 09:51 UTC, Yashk767 commented on config.sh
> +read -rp "Buffer Percent: (20) " BUFFER
yes, the staker would set the config values accordingly for 5 min epoch and the desired input would also lie in the given range limit.

2024-05-08 09:52 UTC, ashish10677 approved these changes

2024-05-13 10:19 UTC, rajkharvar approved these changes

2024-05-14 10:32 UTC, merged