feat: Implemented batching of multiple getStakeSnapshot RPC calls
razor-network/oracle-node pull request #1218
Opened 2024-06-19 03:55 UTC by Yashk767

# Description

Implemented a RPC batch call implementation to get stakeSnapshot values for all the stakers in calculating biggest staker.

Fixes #1217

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Contracts version:
* Hardware:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-19 19:44 UTC, ashish10677 requested changes

2024-06-19 19:44 UTC, ashish10677 commented on cmd/propose.go
> +	voteManagerABI, err := utils.ABIInterface.Parse(strings.NewReader(bindings.VoteManagerMetaData.ABI))
You can get the ABI just by doing, `bindings.VoteManagerMetaData.GetAbi()`

2024-06-19 19:44 UTC, ashish10677 commented on cmd/propose.go
> +		data, err := voteManagerABI.Pack("getStakeSnapshot", epoch, uint32(i))
Add "getStakeSnapshot" to constants

2024-06-21 09:19 UTC, Yashk767 commented on cmd/propose.go
> +	voteManagerABI, err := utils.ABIInterface.Parse(strings.NewReader(bindings.VoteManagerMetaData.ABI))
If I use `GetAbi()` from bindings I wont be able to mock it and cover a case of error in parsing voteManager Abi therefor I just used our existing `AbiInterface.Parse()` which does the same function `abi.Abi()` internally.

2024-07-19 11:21 UTC, Yashk767 commented on cmd/propose.go
> +		data, err := voteManagerABI.Pack("getStakeSnapshot", epoch, uint32(i))
Done in https://github.com/razor-network/oracle-node/pull/1218/commits/b7f79ae4f81ca23e0eb97e82c6acfca751d5e296

2024-07-19 11:23 UTC, Yashk767 commented
Updated the target branch from `develop` to new rebased `feature/v1.2.0` branch.
So there was a need to rebase the base branch.
cc @ashish10677 @rajkharvar

2024-07-19 13:11 UTC, ashish10677 commented
I think we should implement batch calls with retry @Yashk767 to avoid issues in future.

2024-07-22 09:32 UTC, Yashk767 commented
> I think we should implement batch calls with retry @Yashk767 to avoid issues in future.

yes okay makes sense, we can have a generic batch function with retry implemented in the same way we did at other place.  @ashish10677

2024-07-25 09:33 UTC, Yashk767 commented
> I think we should implement batch calls with retry @Yashk767 to avoid issues in future.

Implemented with covering all test scenarios in https://github.com/razor-network/oracle-node/pull/1218/commits/08edf3d85a6a2d35cd42aa85f519c52703e10814
cc @ashish10677 @rajkharvar

2024-07-25 14:38 UTC, ashish10677 requested changes

2024-07-26 04:47 UTC, Yashk767 commented on cmd/propose.go
>  		case <-stateTimeout.C:
I think yes, we can remove it now. we just iterate over the stakeArray list of len(numOfStakers).

2024-07-26 05:16 UTC, Yashk767 commented on cmd/propose.go
>  		case <-stateTimeout.C:
Done in https://github.com/razor-network/oracle-node/pull/1218/commits/7fd941d6bc64b77c338da5296c5771d4d6592da1 @ashish10677

2024-07-29 09:18 UTC, ashish10677 approved these changes

2024-07-29 10:21 UTC, rajkharvar approved these changes

2024-07-30 07:40 UTC, merged