refactor: replaced SKL with sFuel as a gas token in logs
razor-network/oracle-node pull request #1253
Opened 2024-10-04 10:34 UTC by Yashk767

# Description

Currently SKL is being logged as  gas token, SKL is never used as an gas ans sfuel and the SKL token are different.
Replaced SKL with sFuel in logs.

2024-10-04 10:36 UTC, yohanelly95 commented
@Yashk767 @ashish10677 the min amount will most probably be 0.1 sfuel since the faucet disperses only 0.1 sfuel. Change it to 0.001 sfuel or so imo

2024-10-04 10:37 UTC, Yashk767 commented
> @Yashk767 @ashish10677 the min amount will most probably be 0.1 sfuel since the faucet disperses only 0.1 sfuel. Change it to 0.001 sfuel or so imo

True, makes sense

2024-10-08 11:13 UTC, ashish10677 approved these changes
lgtm

2024-10-09 05:04 UTC, rajkharvar commented
@Yashk767 There are other instances where 'sFUEL' is being used. Could you perform a global search and update them as well?

2024-10-09 05:06 UTC, ashish10677 commented
> @Yashk767 There are other instances where 'sFUEL' is being used. Could you perform a global search and update them as well?

Using sFuel is fine. Using SKL isn't.

2024-10-09 05:09 UTC, rajkharvar submitted a review, later dismissed

2024-10-09 05:10 UTC, yohanelly95 approved these changes

2024-10-09 05:11 UTC, yohanelly95 requested changes

2024-10-09 05:11 UTC, yohanelly95 commented on cmd/vote.go
> +	if ethBalance.Cmp(big.NewInt(1e15)) == -1 {
@Yashk767 should be `sFUEL` this is from Skales portal

2024-10-09 05:16 UTC, Yashk767 commented on cmd/vote.go
> +	if ethBalance.Cmp(big.NewInt(1e15)) == -1 {
I think its fine as its a variable name `ethBalance` as on oracle node all the variables and functions are related to gas are named with eth  like `var ethBalance`, `func CheckEthBalanceIsZero()`. This should work right?

While in logs and comments we have changed it to sFuel wherever required.

2024-10-09 10:26 UTC, Yashk767 commented on cmd/vote.go
> +	if ethBalance.Cmp(big.NewInt(1e15)) == -1 {
@yohanelly95 does this make sense? elsewhere SKL is changed to sFuel wherever needed in comments and logs.

2024-10-09 10:39 UTC, Yashk767 commented on cmd/vote.go
> +	if ethBalance.Cmp(big.NewInt(1e15)) == -1 {
ohh did you mean to use `sFUEL` instead of `sFuel` ?

2024-10-09 11:05 UTC, yohanelly95 commented on cmd/vote.go
> +	if ethBalance.Cmp(big.NewInt(1e15)) == -1 {
yes use sFUEL instead of sFuel @Yashk767

2024-10-10 08:50 UTC, Yashk767 commented on cmd/vote.go
> +	if ethBalance.Cmp(big.NewInt(1e15)) == -1 {
Done in https://github.com/razor-network/oracle-node/pull/1253/commits/93487e9adf49659f95cf6d37a26813618863a8a1

2024-10-14 10:30 UTC, yohanelly95 approved these changes

2024-10-14 11:23 UTC, ashish10677 approved these changes

2024-10-15 04:05 UTC, rajkharvar approved these changes

2024-10-15 08:14 UTC, merged