Added password flag
razor-network/oracle-node pull request #946
Opened 2022-09-15 18:30 UTC by shekhar2807

# Description

- Added password flag in node.
- Modified tests according to the changes

fixes #941

2022-09-22 06:45 UTC, ashish10677 requested changes

2022-09-22 06:45 UTC, ashish10677 commented on README.md
> +>**_NOTE:_**  To run command with password flag, password file should present in $HOME/.razor/ directory
Modify this

2022-09-22 07:48 UTC, shekhar2807 commented on README.md
> +>**_NOTE:_**  To run command with password flag, password file should present in $HOME/.razor/ directory
Done @ashish10677

2022-09-26 06:26 UTC, ashish10677 approved these changes

2022-09-26 06:34 UTC, Yashk767 approved these changes

2022-09-26 07:36 UTC, merged