Changed pending nonce at to nonce at.
razor-network/oracle-node pull request #948
Opened 2022-09-26 18:19 UTC by ashish10677

# Description

`PendingNonceAt` is changed to `NonceAt`

Fixes [#114](https://github.com/razor-network/bridge-node/issues/114)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Tested on local hardhat network
- [ ] Tested all the test cases.

2022-09-27 13:27 UTC, Yashk767 requested changes

2022-09-27 13:27 UTC, Yashk767 commented on utils/mocks/abi_utils.go
> +// Code generated by mockery v2.9.4. DO NOT EDIT.
All mockery generated files in utils pkg have changed their version 
It's not affecting the tests but should we update mockery to the latest version? so that generated mocks will be in sync for all of us.
@ashish10677.

2022-09-27 14:06 UTC, ashish10677 commented on utils/mocks/abi_utils.go
> +// Code generated by mockery v2.9.4. DO NOT EDIT.
Hmmm, for this we'll have to update the go.mod file right? @Yashk767

2022-09-30 08:45 UTC, Yashk767 commented on utils/mocks/abi_utils.go
> +// Code generated by mockery v2.9.4. DO NOT EDIT.
Yes we can do that.
Its not required for the build though, we just need to have common version for dev purpose.  
We can just decide it externally too.

2022-09-30 13:04 UTC, ashish10677 commented on utils/mocks/abi_utils.go
> +// Code generated by mockery v2.9.4. DO NOT EDIT.
Fixed @Yashk767

2022-09-30 13:34 UTC, shekhar2807 approved these changes

2022-09-30 13:34 UTC, merged